name: Update submodules

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */2 * * *"
permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - name: Pull submodules recursively
        run: |
          git submodule update --init --recursive --remote

      - name: Commit and push changes
        run: |
          git config --global user.name ${{ secrets.USER_NAME }}
          git config --global user.email ${{ secrets.USER_EMAIL }}
          git commit -am "Update submodules"
          git push
